version: 0.2
phases:
  install:
    commands:
    - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://0.0.0.0:2375 --storage-driver=overlay&
    - timeout -t 15 sh -c "until docker info; do echo .; sleep 1; done"
  build:
    commands:
    - sbt ";compile ;docker:stage ;docker:publishLocal"
artifacts:
  files:
  - '**/*'
  discard-paths: no
cache:
  paths:
  - '/root/.ivy2/cache/**/*'
